### ISSUE TITLE
ImportError: BartForConditionalGeneration requires the PyTorch library but it was not found in your environment

### ISSUE THREAD

**Issue by faaizshah** [ozgur142/TextSummarization#1]
I tried to run your program by following the README. It's not working for me. Here are the images of errors for your reference. 

It would be nice if you can create a Dockerfile of your application.

![Screenshot from 2024-02-29 14-46-01](https://github.com/ozgur142/TextSummarization/assets/32441119/2e0eb8f2-3c9f-460a-a878-fb63db5af6a3)
![Screenshot from 2024-02-29 14-45-39](https://github.com/ozgur142/TextSummarization/assets/32441119/44ce7d00-bd4f-49fe-8c68-2b0630d1a1f3)
![Screenshot from 2024-02-29 14-45-03](https://github.com/ozgur142/TextSummarization/assets/32441119/55e8c669-e5b8-4c9e-9dd3-936e6dd83714)

**Comment by ozgur142** [comment]
Neccesary libraries to download are added to 'requirements.txt'
